@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyb2d1ZWxpa2UiLCJzdWIiOiJwYWdvdG8iLCJpZCI6MSwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY0NjIzNDcyOH0.ds7FAKI_IL6eMqllHyZSv2myOwTjcMQas_zorlxIcEo
@url = http://localhost:8080/api/game
@host = http://localhost:8080

GET {{url}} HTTP/1.1

###

GET {{url}}/1 HTTP/1.1
Authorization: Bearer {{jwt}}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "score": 300,
    "blueprint": true
    
}



###
PUT {{url}}/edit/4 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}


{
    "gameId": 4,
    "score": 200,
    "isBlueprint": "true"
}

###
DELETE {{url}}/4 HTTP/1.1
Authorization: Bearer {{jwt}}

